import type { Metadata } from "next";
import "../style/globals.css";
import "../style/drawer.css";
import { Providers } from "@/lib/provider";
import MainLayout from "./checkerLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/public/logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Providers>
          <MainLayout>{children}</MainLayout>
        </Providers>
      </body>
    </html>
  );
}
